#!/bin/sh
# $FreeBSD$

# PROVIDE: pwrd
# REQUIRE: DAEMON cleanvar devd
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf to enable pwrd:
# pwrd_enable (bool):		Set to "NO" by default.
#				Set it to "YES" to enable syscache 

. /etc/rc.subr

name=pwrd
rcvar=pwrd_enable
pidfile="/var/run/${name}.pid"
command="/usr/sbin/daemon"
command_args="-f -p ${pidfile} /usr/local/sbin/${name}"

start_precmd="pwrd_start"
stop_postcmd="pwrd_stop"

pwrd_stop()
{
   if [ -e "$pidfile" ] ; then
    rm $pidfile >/dev/null 2>/dev/null
   fi
   if [ -e "/var/run/pwrd.pipe" ] ; then
    rm /var/run/pwrd.pipe >/dev/null 2>/dev/null
   fi
   
}

pwrd_start()
{
  export PATH="${PATH}:/usr/local/bin:/usr/local/sbin"
  #pwrd_stop

  if [ -e "/var/run/pwrd.pipe" ] ; then
    rm /var/run/pwrd.pipe >/dev/null 2>/dev/null
  fi
  
  #/usr/local/sbin/pwrd -d >/dev/null 2>/dev/null
  export PATH="${PATH}:/usr/local/bin:/usr/local/sbin"
  # `$command $command_args` 
}

load_rc_config $name
run_rc_command "$1"